### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by conotation** [real0131/MalangBookFront#2]
비밀번호 찾기식

id, 질문(selectior), 질문 답안

보내는 형식으로 변경 및 수정

**Comment by conotation** [comment]
아 그리고 그 글쓰는 부분부터 작업해주셍
그쪽 db도 새로짜야되니

**Comment by real0131** [comment]
비밀번호 찾기 답변 변경 완료

**Comment by conotation** [comment]
Login.html ( 로그인 페이스북 연동 지우고) -> Mypage.html ( 일부수정 ) -> newBook.html (작업순)

**Comment by real0131** [comment]
에디터 일단은 완료
